package HealthCare.entity;

public enum Speciality {
    NONE,
    FAMILY,
    INTERNAL,
    PEDIATRICS,
    CARDIOLOGY,
    ORTHOPEDICS,
    DERMATOLOGY,
    OPHTHALMOLOGY,
    GASTROENTEROLOGY,
    OBSTETRICS,
    NEUROLOGY,
    PSYCHIATRY,
    EMERGENCY,
    ANESTHESIOLOGY,
    RADIOLOGY,
    PULMONOLOGY,
    ONCOLOGY,
    UROLOGY,
    ENDOCRINOLOGY,
    GYNECOLOGY,
    GYNECOLOGICONCOLOGY
}